# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: iso 0.2.2 ruby lib

Gem::Specification.new do |s|
  s.name = "iso"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Christopher Dell"]
  s.date = "2015-06-21"
  s.description = "A subset of the ISO spec implemented in ruby"
  s.email = "chris@tigrish.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "data/iso-3166-1.yml",
    "data/iso-639-1.yml",
    "data/un-m49.yml",
    "iso.gemspec",
    "lib/iso.rb",
    "lib/iso/language.rb",
    "lib/iso/region.rb",
    "lib/iso/subtag.rb",
    "lib/iso/tag.rb",
    "lib/iso/un/region.rb",
    "locales/en.yml",
    "locales/fr.yml",
    "spec/fixtures/base.yml",
    "spec/lib/iso/language_spec.rb",
    "spec/lib/iso/region_spec.rb",
    "spec/lib/iso/subtag_spec.rb",
    "spec/lib/iso/tag_spec.rb",
    "spec/lib/iso/un/region_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/tigrish/iso"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "A ruby implementation of ISO"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<localeapp>, [">= 0"])
    else
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<localeapp>, [">= 0"])
    end
  else
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<localeapp>, [">= 0"])
  end
end

